YUI.add("yuidoc-meta", function(Y) {
   Y.YUIDoc = { meta: {
    "classes": [
        "ApplicationInitializer",
        "ApplicationInstanceInitializer",
        "BaseModel",
        "ColsconfigDialogContentComponent",
        "DS.ODataAdapter",
        "DS.Projection",
        "DetailEditFormController",
        "DetailInterationService",
        "DeviceService",
        "EditFormController",
        "EditFormNewRoute",
        "EditFormRoute",
        "EnumCaptionHelper",
        "ErrorableControllerMixin",
        "FileTransform",
        "FlexberryBaseComponent",
        "FlexberryCheckboxComponent",
        "FlexberryDatePicker",
        "FlexberryDropDown",
        "FlexberryEnumTransform",
        "FlexberryField",
        "FlexberryFileCompatibleComponentMixin",
        "FlexberryFileComponent",
        "FlexberryFileControllerMixin",
        "FlexberryFileViewDialogController",
        "FlexberryGroupeditComponent",
        "FlexberryGroupeditRouteMixin",
        "FlexberryLookup",
        "FlexberryLookupCompatibleComponent",
        "FlexberryLookupMixin",
        "FlexberryMenu",
        "FlexberryMenuitem",
        "FlexberryObjectlistview",
        "FlexberryObjectlistviewRouteMixin",
        "FlexberrySimpledatetime",
        "FlexberryTextarea",
        "FlexberryTextbox",
        "FlexberryToggler",
        "FlexberryValidationmessage",
        "FlexberryValidationsummary",
        "GroupEditToolbarComponent",
        "IISCaseberryLoggingObjectsApplicationLogEController",
        "IISCaseberryLoggingObjectsApplicationLogERoute",
        "IISCaseberryLoggingObjectsApplicationLogLController",
        "IISCaseberryLoggingObjectsApplicationLogLRoute",
        "IISCaseberryLoggingObjectsApplicationLogModel",
        "IISCaseberryLoggingObjectsApplicationLogSerializer",
        "LimitedController",
        "LimitedRouteMixin",
        "ListFormController",
        "ListFormRoute",
        "LogService",
        "LookupDialogController",
        "Mobile.FlexberryFileComponent",
        "Mobile.FlexberryGroupeditComponent",
        "Mobile.FlexberryObjectlistview",
        "Mobile.ObjectListViewComponent",
        "ModalApplicationRoute",
        "ModalDialog",
        "NewPlatformFlexberryFlexberryUserSettingModel",
        "NewPlatformFlexberryFlexberryUserSettingSerializer",
        "ObjectListViewCell",
        "ObjectListViewComponent",
        "ObjectListViewHeaderCell",
        "ObjectListViewSingleColumnCellComponent",
        "ObjectlistviewEvents",
        "OlvToolbar",
        "PaginatedController",
        "ProjectedModelForm",
        "Query.BaseAdapter",
        "Query.BaseBuilder",
        "Query.BasePredicate",
        "Query.Builder",
        "Query.ComplexPredicate",
        "Query.Condition",
        "Query.DetailPredicate",
        "Query.FilterOperator",
        "Query.IndexedDbAdapter",
        "Query.JSAdapter",
        "Query.ODataAdapter",
        "Query.OrderByClause",
        "Query.SimplePredicate",
        "Query.StringPredicate",
        "ReloadListMixin",
        "Resolver",
        "Serializer.Base",
        "Serializer.OData",
        "SortableColumn",
        "SortableControllerMixin",
        "SortableRoute",
        "UIMessage",
        "UserSettingsService",
        "Utils.Information",
        "ValidationDataObject"
    ],
    "modules": [
        "ember-flexberry",
        "ember-flexberry-data"
    ],
    "allModules": [
        {
            "displayName": "ember-flexberry",
            "name": "ember-flexberry"
        },
        {
            "displayName": "ember-flexberry-data",
            "name": "ember-flexberry-data",
            "description": "Ember Addon that adds support of projections in models."
        }
    ],
    "elements": []
} };
});